<UL style="BORDER-BOTTOM-STYLE: dotted; BORDER-BOTTOM-COLOR: gray; BORDER-TOP-COLOR: gray; MARGIN: 0px 0px 5px; BORDER-LEFT-STYLE: dotted; BORDER-TOP-STYLE: dotted; HEIGHT: 173px; BORDER-RIGHT-COLOR: gray; BORDER-RIGHT-STYLE: dotted; BORDER-LEFT-COLOR: gray" class=ui-sortable>
<DIV id=groupArea>
<DIV style="WIDTH: 50%; DISPLAY: inline" id=editGroupArea>Group Name<INPUT style="WIDTH: 70%" id=groupName name=groupName value=test></DIV>
<DIV style="WIDTH: 50%; DISPLAY: none" id=viewGroupArea><SPAN></SPAN></DIV>
<DIV style="TEXT-ALIGN: right; WIDTH: 49%; DISPLAY: none" id=groupMenuArea><A style="CURSOR: pointer" id=sss>removeGroup</A></DIV></DIV>
<LI style="HEIGHT: 81px" class=ui-state-default>
<DIV style="TEXT-ALIGN: right" id=menuArea><SPAN class="ui-icon ui-icon-arrowthick-2-n-s"></SPAN><A style="PADDING-RIGHT: 3px; CURSOR: pointer" id=indentToLeft>◀</A><A style="PADDING-RIGHT: 3px; CURSOR: pointer" id=indentToRight>▶</A><A style="PADDING-RIGHT: 3px; CURSOR: pointer" id=editRow value="edit">edit</A><A style="PADDING-RIGHT: 3px; CURSOR: pointer" id=addRow>add</A><A style="PADDING-RIGHT: 3px; CURSOR: pointer" id=removeRow>remove</A></DIV>
<DIV id=titleArea>
<DIV style="DISPLAY: none" id=editTitleArea><INPUT style="WIDTH: 50%" name=_fieldlabel value=aa><A style="PADDING-LEFT: 3px; CURSOR: pointer" id=titleBold value="off">B</A><A style="PADDING-LEFT: 3px; CURSOR: pointer" id=titleItalic value="off">I</A><A style="PADDING-LEFT: 3px; CURSOR: pointer" id=titleUnderline value="off">U</A><A style="PADDING-LEFT: 3px; CURSOR: pointer" id=titleCancelline value="off">C</A></DIV>
<DIV id=viewTitleArea><SPAN style="FONT-WEIGHT: normal">aa</SPAN></DIV></DIV>
<DIV id=fieldArea>
<DIV style="DISPLAY: none" id=editFieldArea>
<DIV id=rowEditFieldArea><INPUT style="WIDTH: 50%" name=text></DIV></DIV>
<DIV id=viewFieldArea>
<DIV id=rowViewFieldArea><INPUT style="WIDTH: 50%" id=in name=in viewMode="0"></DIV></DIV></DIV>
<DIV style="DISPLAY: none" id=attributeArea><SPAN style="PADDING-RIGHT: 3px" id=_fieldTypeTitle>Field Type</SPAN><SELECT name=_fieldType><OPTION value=title>Title</OPTION><OPTION selected value=text>Text</OPTION><OPTION value=richtext>RichText</OPTION><OPTION value=combobox>Combobox</OPTION><OPTION value=checkbox>Checkbox</OPTION><OPTION value=radio>Radio</OPTION><OPTION value=finduser>UserPicker</OPTION><OPTION value=calendartag>Calendar</OPTION><OPTION value=fileupload>FileUpload</OPTION><OPTION value=separator>Separator</OPTION></SELECT> <SPAN style="PADDING-LEFT: 5px; PADDING-RIGHT: 3px; DISPLAY: inline" id=_fieldNameTitle>Field Id</SPAN> <INPUT style="DISPLAY: inline" name=_fieldName value=in><SPAN style="PADDING-LEFT: 5px; PADDING-RIGHT: 3px; DISPLAY: inline" id=_fieldViewModeTitle>View Mode</SPAN> <INPUT style="DISPLAY: inline" name=_fieldViewMode type=checkbox><SPAN style="PADDING-LEFT: 5px; PADDING-RIGHT: 3px; DISPLAY: none" id=_fieldAttributeTitle>Field Attribute</SPAN> <SELECT style="DISPLAY: none" name=_fieldAttribute></SELECT> <INPUT name=_fieldAttributeKey type=hidden></DIV></LI>
<LI style="HEIGHT: 76px" class=ui-state-default>
<DIV style="TEXT-ALIGN: right" id=menuArea><SPAN class="ui-icon ui-icon-arrowthick-2-n-s"></SPAN><A style="PADDING-RIGHT: 3px; CURSOR: pointer" id=indentToLeft>◀</A><A style="PADDING-RIGHT: 3px; CURSOR: pointer" id=indentToRight>▶</A><A style="PADDING-RIGHT: 3px; CURSOR: pointer" id=editRow value="edit">edit</A><A style="PADDING-RIGHT: 3px; CURSOR: pointer" id=addRow>add</A><A style="PADDING-RIGHT: 3px; CURSOR: pointer" id=removeRow>remove</A></DIV>
<DIV id=titleArea>
<DIV style="DISPLAY: none" id=editTitleArea><INPUT style="WIDTH: 50%" name=_fieldlabel value=user><A style="PADDING-LEFT: 3px; CURSOR: pointer" id=titleBold value="off">B</A><A style="PADDING-LEFT: 3px; CURSOR: pointer" id=titleItalic value="off">I</A><A style="PADDING-LEFT: 3px; CURSOR: pointer" id=titleUnderline value="off">U</A><A style="PADDING-LEFT: 3px; CURSOR: pointer" id=titleCancelline value="off">C</A></DIV>
<DIV style="DISPLAY: block" id=viewTitleArea><SPAN style="FONT-WEIGHT: normal">user</SPAN></DIV></DIV>
<DIV style="DISPLAY: block" id=fieldArea>
<DIV style="DISPLAY: none" id=editFieldArea>
<DIV id=rowEditFieldArea><IMG style="HEIGHT: 15px" id=fakeImage name=fakeImage src="http://localhost:8080/uengine-web/processmanager/images/finduser.gif"></DIV></DIV>
<DIV style="DISPLAY: block" id=viewFieldArea>
<DIV id=rowViewFieldArea> <?xml:namespace prefix = input /><input:finduser name="u" multiple="false" viewMode="0"></input:finduser></DIV></DIV></DIV>
<DIV style="DISPLAY: none" id=attributeArea><SPAN style="PADDING-RIGHT: 3px" id=_fieldTypeTitle>Field Type</SPAN><SELECT name=_fieldType><OPTION value=title>Title</OPTION><OPTION value=text>Text</OPTION><OPTION value=richtext>RichText</OPTION><OPTION value=combobox>Combobox</OPTION><OPTION value=checkbox>Checkbox</OPTION><OPTION value=radio>Radio</OPTION><OPTION selected value=finduser>UserPicker</OPTION><OPTION value=calendartag>Calendar</OPTION><OPTION value=fileupload>FileUpload</OPTION><OPTION value=separator>Separator</OPTION></SELECT> <SPAN style="PADDING-LEFT: 5px; PADDING-RIGHT: 3px; DISPLAY: inline" id=_fieldNameTitle>Field Id</SPAN> <INPUT style="DISPLAY: inline" name=_fieldName value=u><SPAN style="PADDING-LEFT: 5px; PADDING-RIGHT: 3px; DISPLAY: inline" id=_fieldViewModeTitle>View Mode</SPAN> <INPUT style="DISPLAY: inline" name=_fieldViewMode type=checkbox><SPAN style="PADDING-LEFT: 5px; PADDING-RIGHT: 3px; DISPLAY: inline" id=_fieldAttributeTitle>Field Attribute</SPAN> <SELECT style="DISPLAY: inline" name=_fieldAttribute><OPTION value=true>Multiple</OPTION><OPTION selected value=false>Single</OPTION></SELECT> <INPUT name=_fieldAttributeKey value=multiple type=hidden></DIV></LI></UL>
<DIV style="TEXT-ALIGN: right; WIDTH: 100%; MARGIN-RIGHT: 13px" id=addGroupMenu class=ui-state-disabled><A style="PADDING-RIGHT: 3px; CURSOR: pointer" id=addGroup>addGroup</A></DIV>